_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "ProposalNetwork"
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "/home/leiyvtian/Project/detectron2/model_weights/model_final_02ce48.pkl"
  WEIGHTS: "/home/leiyvtian/Project/detectron2/model_weights/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  RPN:
    POST_NMS_TOPK_TEST: 2000
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
#  TEST: ('voc_custom_val',)
  TEST: ('coco_2017_val',)
#  TEST: ('coco_extended_ood_val',)
#  TEST: ('coco_mixed_val',)
#SOLVER:
#  IMS_PER_BATCH: 16
#  BASE_LR: 0.02
#  STEPS: (60000, 80000)
#  MAX_ITER: 90000
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (12000, 16000)
  BASE_LR: 0.02
  MAX_ITER: 18000  # 17.4 epochs
  WARMUP_ITERS: 100
